SQL updates
SysKitTeam/docs-point pull request #195
Opened 2022-10-03 14:48 UTC by katperich

Updates to articles and new Managed Identity article.

2022-10-04 14:52 UTC, imesaric requested changes
baciti u grammarly, vidio sam par spellcheck errora
za sad sam pogledao samo tekst, sutra ćemo riješiti i access za screenshotove ili kreirati novi environment gdje ćeš moći to odraditi

2022-10-04 14:52 UTC, imesaric commented on installation/deploy-syskit-point.md
> +**Please note!** This is mandatory in order to **provision a new SQL server** as this is a Microsoft requirement. Without using the SQL credentials, it would not be possible to create the SQL server,
fali mi još objašnjenje da nakon initial provisionanja servera, SQL auth se disablea, i dalje koristi managed identity

2022-10-04 14:52 UTC, imesaric commented on installation/managed-identity-authentication.md
> +---
članak bi možda rađe stavio u configuration folder i dao mu title upgrade-SQL-to-managed-identity-authentication.md

2022-10-04 14:52 UTC, imesaric commented on installation/managed-identity-authentication.md
> +
fali mi objašnjenje u uvodu - ovo moraju odraditi samo oni koji su imali deployan Point prije v2022.5 i sad nakon upgradea na v2022.5 žele koristiti SQL sa MI authenticationom
novi korisnici koji odmah idu deployat v2022.5 će by default imati SQL MI auth umjesto SQL auth

2022-10-04 14:52 UTC, imesaric commented on installation/managed-identity-authentication.md
> +
naglasio bih isto tako da nakon upgradea na v2022.5 se i dalje koristi SQL auth
ako se želi koristiti SQL MI, follow upute u ovom članku

2022-10-04 14:52 UTC, imesaric commented on installation/managed-identity-authentication.md
> +After successfully setting this up, the next step will be removing the information you've entered.
umjesto removing information bolje reči removing access granted to perform changes, in order to secure SysKit Point Azure resources
jer u ovim gore koracima si daješ pristup sa svog IPa, pa treba to natrag zatvoriti

2022-10-04 14:52 UTC, imesaric commented on power-bi-app/requirements.md
> +
gore u dijelu gdje se na početku članka kaže koji stepovi se moraju completeati ('the following steps need to be completed:'), dodati i 'Enable SQL authentication' ili tako nešto

2022-10-04 14:52 UTC, imesaric commented on power-bi-app/requirements.md
ovdje staviti novi ## title kao i za svaki drugi step

2022-10-05 13:25 UTC, imesaric commented on installation/managed-identity-authentication.md
> +* For **Find Principal select the Admin** that is completing the Managed Identity authentication process and click **Next**
ovdje bih stavio 'Find and select your account and click Next; with this you will gain permissions to perform changes in the key vault'

2022-10-05 13:57 UTC, imesaric commented on installation/managed-identity-authentication.md
> +* Under **Review + Create, select the principal name** of the person that was selected in the previous step
u koraku Review + create samo treba kliknuti Create i to je to

2022-10-06 10:31 UTC, imesaric commented on installation/managed-identity-authentication.md
> +* Under Firewall, **click Add your client IP address** and **paste your public IP address** here
ispred još fali odabir opcije Allow public access from specific virtual networks and public IP addresses

2022-10-06 13:39 UTC, imesaric commented on installation/managed-identity-authentication.md
> +This part of the text: User Id="{**managed identity client id**} needs to be changed. The Client ID you previously copied from your Managed Identity resource should be placed where the text says **ma
ne mijenja se samo taj dio texta, nego i {servername}, znači treba i na početku otvoriti SQL server resurs i tamo uzeti Serrver name. S tim da bi tu onda stavio da umjesto {servername}.database.windows.net piše samo {serverName}, jer se u na SQL resursu lako može kopirati na taj način https://sharexuploadsstorage.blob.core.windows.net/sharexuploads/ShareX/2022/10/IMESARIC_06.10.2022_15.38.36.png

2022-10-06 13:42 UTC, imesaric commented on installation/managed-identity-authentication.md
> +   * This will be needed later, so store the copied text somewhere it will be easy to get it later
treba još dodati i korak otvaranja SQL server resursa + copy Server Name-a jer je potreban dalje u koracima

2022-10-06 14:26 UTC, imesaric commented on installation/managed-identity-authentication.md
> +* **Choose the Managed Identity** that was used in the previous steps
tu bi trebalo ići:
u search upisati client ID od managed identitya (kopirano na početku)
select

2022-10-06 14:29 UTC, imesaric commented on power-bi-app/requirements.md
> +* On the home page of the SQL server, under **Features**, click the **Active Directory admin** bubble
under Settings; click the AAD option umjesto bubble

2022-10-13 11:53 UTC, zlatkoHrastic commented on configuration/upgrade-SQL-to-managed-identity-authentication.md
> +Those that deployed SysKit Point before that release will need to manually upgrade to Managed Identity.
Ovaj need mi je prejaka riječ, išao bi s can, zato što ne mroaju ići na MI

2022-10-13 11:59 UTC, zlatkoHrastic commented on configuration/upgrade-SQL-to-managed-identity-authentication.md
> +{% endhint %}
Možda dodati primjer?
Data Source=tcp:contoso.database.windows.net,1433;Initial Catalog=SysKitPointDB;User Id="00000000-0000-0000-0000-000000000000";Authentication=Active Directory Managed Identity;

2022-10-13 12:02 UTC, zlatkoHrastic commented on configuration/upgrade-SQL-to-managed-identity-authentication.md
> +* **Under Networking, remove your IP address**
Fali, set Public network access to Disabled
![image](https://user-images.githubusercontent.com/12006653/195590910-214bb66e-fdd4-4496-a55f-95a5d8c55cc0.png)

2022-10-13 12:03 UTC, zlatkoHrastic commented on configuration/upgrade-SQL-to-managed-identity-authentication.md
> +* **Under Networking, remove your IP address**
nope, krivi resurs,s ry

2022-10-14 13:44 UTC, merged