Matej vnext
SysKitTeam/docs-point pull request #43
Opened 2021-07-12 11:24 UTC by matejper

izmjene na člancima - Turn On Auditing i Customize Audit Logs Collection

2021-07-14 12:58 UTC, imesaric commented on configuration/customize-audit-logs-collection.md
> +![Connect Tenant step](../.gitbook\assets\customize-audit-logs-collection_connect-tenant-step.png)
u svim linkovima treba promijeniti \ u /
trenutno zbog toga ne rade slike

2021-07-14 12:59 UTC, imesaric requested changes
treba obavezno srediti linkove da rade

2021-07-14 13:28 UTC, matejper commented on configuration/customize-audit-logs-collection.md
> +![Connect Tenant step](../.gitbook\assets\customize-audit-logs-collection_connect-tenant-step.png)
izmjenio sam linkove

2021-07-16 06:44 UTC, imesaric approved these changes

2021-07-16 06:44 UTC, merged